<?php


namespace App\Models;


use App\Helpers\ShortIdGeneratorHelper;
use Illuminate\Database\Eloquent\Builder;
use Illuminate\Database\Eloquent\Model;

/**
 * @method static Builder findByShortId(string $short_id)
 */
class BaseModelWithAutoGeneratedShortId extends Model
{
    protected static function boot()
    {

        static::creating(function ($entity) {
            $entity->short_id = ShortIdGeneratorHelper::genIdForAnEntity($entity);
        });
        parent::boot();
        //static::addGlobalScope(new TeamScope);

    }

    public function scopeFindByShortId($query, $short_id)
    {
        return $query->where('short_id', $short_id);
    }
}
